export const ActionTypes = {
    CLEAN_STATE:"CLEAN_STATE",
    LOGIN_USER_START: "LOGIN_USER_START",
    LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
    LOGIN_USER_FAILURE: "LOGIN_USER_FAILURE",
  
    SIGNUP_USER_START: "SIGNUP_USER_START",
    SIGNUP_USER_SUCCESS: "SIGNUP_USER_SUCCESS",
    SIGNUP_USER_FAILURE: "SIGNUP_USER_FAILURE",
  
  };