export const MENTOR_ACTION_TYPES = {
    FETCH_MENTOR_DASHBOARD_START:"mentor/FETCH_MENTOR_DASHBOARD_START",
    FETCH_MENTOR_DASHBOARD_SUCCESS:"mentor/FETCH_MENTOR_DASHBOARD_SUCCESS",
    FETCH_MENTOR_DASHBOARD_FAILURE:"mentor/FETCH_MENTOR_DASHBOARD_FAILURE",
    SUBMIT_MENTOR_REVIEW_START:"mentor/SUBMIT_MENTOR_REVIEW_START",
    SUBMIT_MENTOR_REVIEW_FAILURE:"mentor/SUBMIT_MENTOR_REVIEW_FAILURE",
};
  