export const SKILLS_USER_ACTION_TYPES = {
    REGISTER_SKILLS_USER_START:"skillsUser/REGISTER_SKILLS_USER_START",
    REGISTER_SKILLS_USER_SUCCESS:"skillsUser/REGISTER_SKILLS_USER_SUCCESS",
    REGISTER_SKILLS_USER_FAILURE:"skillsUser/REGISTER_SKILLS_USER_FAILURE",
};
  