export const SKILLS_USER_ACTION_TYPES = {
    FETCH_REGISTERED_DOMAIN_START:"skillsUser/FETCH_REGISTERED_DOMAIN_START",
    FETCH_REGISTERED_DOMAIN_SUCCESS:"skillsUser/FETCH_REGISTERED_DOMAIN_SUCCESS",
    FETCH_REGISTERED_DOMAIN_FAILURE:"skillsUser/FETCH_REGISTERED_DOMAIN_FAILURE",
    SUBMIT_ASSIGNMENT_START:"skillsUser/SUBMIT_ASSIGNMENT_START",
    SUBMIT_ASSIGNMENT_SUCCESS:"skillsUser/SUBMIT_ASSIGNMENT_SUCCESS",
    SUBMIT_ASSIGNMENT_FAILURE:"skillsUser/SUBMIT_ASSIGNMENT_FAILURE",
};
  