export const SKILLS_USER_ACTION_TYPES = {
    FETCH_REGISTERED_DOMAIN_START:"skillsUser/FETCH_REGISTERED_DOMAIN_START",
    FETCH_REGISTERED_DOMAIN_SUCCESS:"skillsUser/FETCH_REGISTERED_DOMAIN_SUCCESS",
    FETCH_REGISTERED_DOMAIN_FAILURE:"skillsUser/FETCH_REGISTERED_DOMAIN_FAILURE",
};
  